# Site settings
title: Protobuf Java Format
email: none
description: > # this means to ignore newlines until "baseurl:"
  Documentation for https://github.com/bivas/protobuf-java-format
baseurl: "/protobuf-java-format/" # the subpath of your site, e.g. /blog/
url: "https://bivas.github.io" # the base hostname & protocol for your site
twitter_username: none
github_username:  none

# Build settings
markdown: kramdown
